In [24]:
import pandas as pd
from datetime import datetime

In [56]:
url = "https://waterberichtgeving.rws.nl/wbviewer/maak_grafiek.php?loc=KUST_28&set=wigo&nummer=7&format=csv"

In [73]:
df = pd.read_csv(url, sep = ';', decimal = ',', 
                 names= ['date', 'wavePeriod', 'waveHeight', 'SWAN_swellHeight'], usecols = ['date', 'wavePeriod', 'waveHeight'], parse_dates = ['date'], skiprows = 1)

In [74]:
today = datetime.today().strftime('%Y-%m-%d')
df = df.query('date > @today')

In [75]:
df = df.drop(df.tail(1).index)

In [77]:
df['date'] = pd.to_datetime(df.date, format='%Y-%m-%d %H:%M:%S')
df['wavePeriod'] = df['wavePeriod'].astype(float)
df['wavePeriod'] = df['wavePeriod'] / 10
df['wavePeriod'] = df['wavePeriod'].astype(int)
df['waveHeight'] = df['waveHeight'].astype(float).apply(lambda x: x / 100).round(1)

In [78]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d %H:%M:%S')
df.to_json(orient='records')

'[{"date":"2023-04-16 00:00:00","wavePeriod":4,"waveHeight":1.1},{"date":"2023-04-16 01:00:00","wavePeriod":4,"waveHeight":1.1},{"date":"2023-04-16 02:00:00","wavePeriod":4,"waveHeight":1.1},{"date":"2023-04-16 03:00:00","wavePeriod":4,"waveHeight":1.0},{"date":"2023-04-16 04:00:00","wavePeriod":4,"waveHeight":1.0},{"date":"2023-04-16 05:00:00","wavePeriod":4,"waveHeight":1.0},{"date":"2023-04-16 06:00:00","wavePeriod":4,"waveHeight":1.0},{"date":"2023-04-16 07:00:00","wavePeriod":4,"waveHeight":1.0},{"date":"2023-04-16 08:00:00","wavePeriod":4,"waveHeight":0.9},{"date":"2023-04-16 09:00:00","wavePeriod":4,"waveHeight":0.9},{"date":"2023-04-16 10:00:00","wavePeriod":4,"waveHeight":0.9},{"date":"2023-04-16 11:00:00","wavePeriod":4,"waveHeight":0.9},{"date":"2023-04-16 12:00:00","wavePeriod":4,"waveHeight":0.9},{"date":"2023-04-16 13:00:00","wavePeriod":4,"waveHeight":0.8},{"date":"2023-04-16 14:00:00","wavePeriod":4,"waveHeight":0.8},{"date":"2023-04-16 15:00:00","wavePeriod":4,"waveHeight":0.8},{"date":"2023-04-16 16:00:00","wavePeriod":4,"waveHeight":0.7},{"date":"2023-04-16 17:00:00","wavePeriod":4,"waveHeight":0.7},{"date":"2023-04-16 18:00:00","wavePeriod":4,"waveHeight":0.7},{"date":"2023-04-16 19:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-16 20:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-16 21:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-16 22:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-16 23:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-17 00:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-17 01:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-17 02:00:00","wavePeriod":4,"waveHeight":0.6},{"date":"2023-04-17 03:00:00","wavePeriod":3,"waveHeight":0.6},{"date":"2023-04-17 04:00:00","wavePeriod":3,"waveHeight":0.5},{"date":"2023-04-17 05:00:00","wavePeriod":3,"waveHeight":0.5},{"date":"2023-04-17 06:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 07:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 08:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 09:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 10:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 11:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 12:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 13:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 14:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 15:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 16:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 17:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 18:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-17 19:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-17 20:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-17 21:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-17 22:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-17 23:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-18 00:00:00","wavePeriod":2,"waveHeight":0.4},{"date":"2023-04-18 01:00:00","wavePeriod":3,"waveHeight":0.4},{"date":"2023-04-18 02:00:00","wavePeriod":3,"waveHeight":0.5}]'

In [79]:
df

                    date  wavePeriod  waveHeight
455  2023-04-16 00:00:00           4         1.1
456  2023-04-16 01:00:00           4         1.1
457  2023-04-16 02:00:00           4         1.1
458  2023-04-16 03:00:00           4         1.0
459  2023-04-16 04:00:00           4         1.0
460  2023-04-16 05:00:00           4         1.0
461  2023-04-16 06:00:00           4         1.0
462  2023-04-16 07:00:00           4         1.0
463  2023-04-16 08:00:00           4         0.9
464  2023-04-16 09:00:00           4         0.9
465  2023-04-16 10:00:00           4         0.9
466  2023-04-16 11:00:00           4         0.9
467  2023-04-16 12:00:00           4         0.9
468  2023-04-16 13:00:00           4         0.8
469  2023-04-16 14:00:00           4         0.8
470  2023-04-16 15:00:00           4         0.8
471  2023-04-16 16:00:00           4         0.7
472  2023-04-16 17:00:00           4         0.7
473  2023-04-16 18:00:00           4         0.7
474  2023-04-16 19:00:00           4         0.6
475  2023-04-16 20:00:00           4         0.6
476  2023-04-16 21:00:00           4         0.6
477  2023-04-16 22:00:00           4         0.6
478  2023-04-16 23:00:00           4         0.6
479  2023-04-17 00:00:00           4         0.6
480  2023-04-17 01:00:00           4         0.6
481  2023-04-17 02:00:00           4         0.6
482  2023-04-17 03:00:00           3         0.6
483  2023-04-17 04:00:00           3         0.5
484  2023-04-17 05:00:00           3         0.5
485  2023-04-17 06:00:00           3         0.4
486  2023-04-17 07:00:00           3         0.4
487  2023-04-17 08:00:00           3         0.4
488  2023-04-17 09:00:00           3         0.4
489  2023-04-17 10:00:00           3         0.4
490  2023-04-17 11:00:00           3         0.4
491  2023-04-17 12:00:00           3         0.4
492  2023-04-17 13:00:00           3         0.4
493  2023-04-17 14:00:00           3         0.4
494  2023-04-17 15:00:00           3         0.4
495  2023-04-17 16:00:00           3         0.4
496  2023-04-17 17:00:00           3         0.4
497  2023-04-17 18:00:00           3         0.4
498  2023-04-17 19:00:00           2         0.4
499  2023-04-17 20:00:00           2         0.4
500  2023-04-17 21:00:00           2         0.4
501  2023-04-17 22:00:00           2         0.4
502  2023-04-17 23:00:00           2         0.4
503  2023-04-18 00:00:00           2         0.4
504  2023-04-18 01:00:00           3         0.4
505  2023-04-18 02:00:00           3         0.5